name: Update copyright year in license file
on:
  schedule:
    - cron: "0 3 1 1 *" # 03:00 AM on January 1

jobs:
    yaml-lint:
        uses: swissfintechinnovations/.github/.github/workflows/reusable-license-update-workflow.yaml@main