name: Lint yaml-files (reusable)

on:
  pull_request:
  workflow_dispatch:

jobs:
  yaml-lint:
    uses: swissfintechinnovations/.github/.github/workflows/reusable-yamllint-workflow.yaml@main
    with:
        filenames: '*.yaml'
        fail: true
